name: capitalcom
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - cryptography=45.0.5
  - ipykernel=6.29.5
  - loguru=0.7.2
  - matplotlib=3.10.0
  - nbformat=5.10.4
  - numpy=2.3.1
  - pandas=2.3.1
  - plotly=6.0.1
  - pydantic=2.11.7
  - pydantic-settings=2.6.1
  - python=3.12.3
  - python-dotenv=1.1.0
  - pyyaml=6.0.2
  - requests=2.32.4
  - sqlite=3.50.2
  - ta-lib=0.6.4
  - websocket-client=1.8.0
  - yfinance=0.2.65
